# -*- mode:conf; coding:utf-8 -*-

[alias]
    lg0         = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative
    lg1         = log --graph --all --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(bold white)— %an%C(reset)%C(bold yellow)%d%C(reset)' --abbrev-commit --date=relative
    lg2         = log --graph --all --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(bold white)— %an%C(reset)' --abbrev-commit
    lg          = !"git lg1"
    ls          = !"git log --pretty=format: --name-status | cut -f2- | sort -u"
    lgb         = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset%n' --abbrev-commit --date=relative --branches
    gbra        = log --graph --pretty=format:'%Cred%h%C(yellow)%d %C(bold blue)<%an>%Creset %s%n' --abbrev-commit --date=relative --branches
    gbral       = log --graph --abbrev-commit --date=relative --branches --pretty=format:'%Cred%H%C(yellow)%d %C(bold blue)<%an>%Creset %s%n' 
    gbranc      = log --graph --pretty=format:'%h%d <%an> %s%n' --abbrev-commit --date=relative --branches
    gbrs        = log --graph --pretty=format:'%Cred%h%C(yellow)%d%Creset%n' --abbrev-commit --date=relative --branches
    slog        = log --pretty=format:'%Cred%h%C(yellow)%d %C(bold blue)<%an>%Creset %s%n' --abbrev-commit --date=relative
    david       = log --oneline --decorate --graph --abbrev-commit --date=relative --branches
    ss          = status --short
    st          = status
    stat        = status
	curbra      = rev-parse --abbrev-ref HEAD
	curcom      = rev-parse HEAD
    check-email = !"git log --since='4 weeks ago' --pretty=format:'%h | %as | email=%ae | name=%an' | sort -u"
    where-added  = log --diff-filter=A
	show-branches = "!printf '# Local branches:\\n'; git branch -a; printf '# Remote branches:\\n'; git branch -r"
	show-remotes = "!printf '# Remote repositories:\\n'; git remote -v | expand -16"
    show-tags = "!printf '# Tags:\\n'; git for-each-ref refs/tags --format='%(refname:short) -> %(objectname:short) %(subject)'"
	sbra = !git show-branches
	srem = !git show-remotes
    stag = !git show-tags
	commitof = rev-parse
	last = "!f() { for i in $(seq 1 $1); do git name-rev --name-only --exclude=refs/tags/\\* @{-$i}; done; }; f"
