
# [includeIf "gitdir:~/works/qorvo/"]
#   path = ~/works/qorvo/.gitconfig
# 
# [includeIf "gitdir:/aosp-ci/"]
#   path = ~/works/qorvo/.gitconfig
#
# [includeIf "gitdir:~/company_b/"]
#   path = .gitconfig-company_b

# [url "https://partner-android.googlesource.com/kernel/private/gs-google"]
# 	insteadOf = https://aosp-partner-mirror.officeapps.sevenhugs.com/partner/kernel/private/gs-google
# 
# [url "https://partner-android.googlesource.com/platform/prebuilts/boot-artifacts"]
# 	insteadOf = https://aosp-partner-mirror.officeapps.sevenhugs.com/partner/platform/prebuilts/boot-artifacts
# 
# [url "https://partner-android.googlesource.com/platform/tools/repohooks"]
# 	insteadOf = https://aosp-partner-mirror.officeapps.sevenhugs.com/partner/platform/tools/repohooks
#
# [url "https://qorvopbourguignon:yMLefpnTsHRd2apNcAwV@gitlab.com/"]
# 	insteadOf = https://gitlab.com/
