;;; emacs-femnam -- Pascal J. Bourguignon's emacs startup files.
;;; -*- mode:emacs-lisp;lexical-binding:t;coding:utf-8 -*-
;;; Commentary:
;;; Code:

;; (push (cons "#lisp" (format "^%s[0-9]+$" (regexp-opt *femnams*))) erc-ignore-per-channel-alist)
;; (progn (string-match (format "^%s[0-9]+$" (mapcar 'capitalize (regexp-opt *femnams*))) "Mya29") (match-data))(0 5)
;;  (format "^%s[0-9]+$"  (regexp-opt (mapcar 'capitalize *femnams*)))


(defparameter *femnams*
  '("aaliyah" "abbey" "abbie" "abbigail" "abby" "abigail" "addison" "adrian"
    "adriana" "adrianna" "adrienne" "aileen" "aimee" "aisha" "aja"
    "agathe" "agatha"
    "alaina" "alana" "alanna" "alayna" "aleah" "alecia" "alejandra"
    "alena" "alesha" "alessandra" "alex" "alexa" "alexandra" "alexandrea"
    "alexandria" "alexia" "alexis" "alexus" "ali" "alice" "alicia" "alina"
    "alisa" "alisha" "alison" "alissa" "aliyah" "allie" "allison"
    "allyson" "allyssa" "alma" "alondra" "alycia" "alysa" "alysha"
    "alysia" "alyson" "alyssa" "amanda" "amani" "amber" "amelia" "amy"
    "ana" "anabel" "anais" "anastasia" "andrea" "angel" "angela"
    "angelica" "angelina" "angelique" "angie" "anika" "anissa" "anita"
    "anjelica" "ann" "anna" "annamarie" "anne" "annette" "annie" "annika"
    "annmarie" "antoinette" "antonia" "april" "araceli" "ariana" "arianna"
    "ariel" "arielle" "arlene" "asha" "ashanti" "ashely" "ashlee"
    "ashleigh" "ashley" "ashli" "ashlie" "ashly" "ashlyn" "ashlynn"
    "ashton" "asia" "aspen" "astrid" "athena" "aubree" "aubrey" "audra"
    "audrey" "aurora" "autumn" "ava" "avery" "ayana" "ayanna" "ayla"
    "baby" "bailee" "bailey" "barbara" "baylee" "beatrice" "beatriz"
    "belinda" "berenice" "bernadette" "beth" "bethany" "betsy" "betty"
    "beverly" "bianca" "billie" "blair" "blanca" "bobbi" "bobbie" "bonnie"
    "brandi" "brandie" "brandy" "brea" "breana" "breann" "breanna"
    "breanne" "brenda" "brenna" "breonna" "bria" "briana" "brianna"
    "brianne" "bridget" "bridgette" "brielle" "britany" "britney" "britni"
    "brittani" "brittanie" "brittany" "brittney" "brittni" "brook"
    "brooke" "brooklyn" "bryana" "bryanna" "caitlin" "caitlyn" "callie"
    "cameron" "camille" "candace" "candice" "cara" "carina" "carissa"
    "carla" "carlee" "carley" "carli" "carlie" "carly" "carmen" "carol"
    "carolina" "caroline" "carolyn" "carrie" "carson" "casandra" "casey"
    "cassandra" "cassidy" "cassie" "catalina" "catherine" "cayla"
    "cecelia" "cecilia" "celeste" "celia" "celina" "celine" "chandler"
    "chanel" "chantal" "chantel" "charity" "charlene" "charlotte"
    "chasity" "chaya" "chelsea" "chelsey" "chelsi" "chelsie" "cheryl"
    "cheyanne" "cheyenne" "china" "chloe" "christa" "christen" "christian"
    "christiana" "christie" "christin" "christina" "christine" "christy"
    "ciara" "ciera" "cierra" "cindy" "claire" "clara" "clare" "clarissa"
    "claudia" "colleen" "connie" "constance" "cora" "corey" "cori"
    "corina" "corinne" "cortney" "courtney" "cristal" "cristina" "crystal"
    "cynthia" "daisy" "dakota" "dalia" "dallas" "damaris" "dana" "danica"
    "daniela" "daniella" "danielle" "daphne" "dara" "darby" "darcy"
    "darian" "darlene" "dawn" "dayna" "deana" "deanna" "debbie" "deborah"
    "debra" "deja" "delaney" "demi" "denise" "desirae" "desiree"
    "destinee" "destiney" "destini" "destiny" "devan" "devin" "devon"
    "devyn" "diamond" "diana" "diane" "dianna" "dina" "dominique"
    "dominque" "domonique" "donna" "doris" "dorothy" "drew" "dulce"
    "eboni" "ebony" "eden" "edith" "eileen" "elaina" "elaine" "eleanor"
    "elena" "eliana" "elisa" "elisabeth" "elise" "elisha" "elissa" "eliza"
    "elizabeth" "ella" "ellen" "ellie" "elsa" "elyse" "elyssa" "emerald"
    "emilee" "emilia" "emilie" "emily" "emma" "erica" "ericka" "erika"
    "erin" "esmeralda" "essence" "estefania" "esther" "eunice" "eva"
    "evelyn" "fabiola" "faith" "fatima" "felicia" "fiona" "frances"
    "francesca" "franchesca" "francheska" "gabriel" "gabriela" "gabriella"
    "gabrielle" "genesis" "genevieve" "georgia" "georgina" "gianna"
    "gillian" "gina" "giovanna" "giselle" "gladys" "gloria" "grace"
    "graciela" "gretchen" "griselda" "guadalupe" "gwendolyn" "hailee"
    "hailey" "haleigh" "haley" "hali" "halie" "halle" "hallie" "hanna"
    "hannah" "harley" "haylee" "hayley" "haylie" "hazel" "heather"
    "heaven" "heidi" "helen" "helena" "hilary" "hillary" "hollie" "holly"
    "hope" "hunter" "iesha" "iliana" "imani" "india" "infant" "ingrid"
    "irene" "iris" "irma" "isabel" "isabella" "isabelle" "isamar" "itzel"
    "ivette" "ivy" "jackie" "jacklyn" "jaclyn" "jacqueline" "jacquelyn"
    "jada" "jade" "jaime" "jaimie" "jalisa" "jami" "jamie" "jamila" "jana"
    "janae" "janay" "jane" "janelle" "janessa" "janet" "janette" "janice"
    "janie" "janine" "jaqueline" "jasmin" "jasmine" "jayla" "jayme"
    "jazmin" "jazmine" "jazmyn" "jean" "jeanette" "jena" "jenifer" "jenna"
    "jennie" "jennifer" "jenny" "jerrica" "jesse" "jessenia" "jessi"
    "jessica" "jessie" "jessika" "jill" "jillian" "joan" "joana" "joann"
    "joanna" "joanne" "jocelyn" "jodi" "jodie" "joelle" "johanna" "jolene"
    "jordan" "jordyn" "joselyn" "josephine" "josie" "joy" "joyce" "juana"
    "juanita" "judith" "judy" "julia" "juliana" "julianna" "julianne"
    "julie" "juliet" "julissa" "justice" "justina" "justine" "kacey"
    "kaci" "kacie" "kaela" "kaila" "kailee" "kailey" "kailyn" "kaitlin"
    "kaitlyn" "kaitlynn" "kala" "kaleigh" "kaley" "kali" "kalie" "kallie"
    "kalyn" "kara" "karen" "kari" "karina" "karissa" "karla" "karlee"
    "karley" "karli" "karlie" "karly" "kasandra" "kasey" "kassandra"
    "kassidy" "kassie" "katarina" "kate" "katelin" "katelyn" "katelynn"
    "katerina" "katharine" "katherine" "katheryn" "kathleen" "kathrine"
    "kathryn" "kathy" "katie" "katlin" "katlyn" "katlynn" "katrina" "katy"
    "kaycee" "kayla" "kaylee" "kayleigh" "kayley" "kayli" "kaylie"
    "kaylin" "kaylyn" "kaylynn" "keely" "keila" "keisha" "keishla"
    "kelcie" "kelley" "kelli" "kellie" "kelly" "kelsea" "kelsey" "kelsi"
    "kelsie" "kendal" "kendall" "kendra" "kenia" "kennedy" "kenya" "keri"
    "kerri" "kerry" "khadijah" "kia" "kiana" "kianna" "kiara" "kiera"
    "kierra" "kiersten" "kiley" "kimberlee" "kimberley" "kimberly" "kira"
    "kirsten" "kirstie" "kirstin" "kori" "kortney" "kourtney" "krista"
    "kristal" "kristen" "kristi" "kristian" "kristie" "kristin" "kristina"
    "kristine" "kristy" "kristyn" "krysta" "krystal" "kyla" "kylee"
    "kylie" "kyra" "lacey" "lacie" "lacy" "lakeisha" "lana" "lara"
    "larissa" "latasha" "latisha" "latoya" "laura" "laurel" "lauren"
    "laurie" "lauryn" "layla" "lea" "leah" "leandra" "leann" "leanna"
    "leanne" "leeann" "leigh" "leila" "lena" "lesley" "leslie" "lesly"
    "leticia" "lexi" "lexie" "lexus" "liana" "lidia" "liliana" "lillian"
    "lily" "linda" "lindsay" "lindsey" "lisa" "liza" "lizbeth" "lizeth"
    "lizette" "logan" "loren" "lorena" "lori" "lorraine" "lourdes"
    "lucero" "lucia" "lucy" "luz" "lydia" "lyndsey" "lynette" "lynn"
    "macey" "macie" "mackenzie" "macy" "madalyn" "maddison" "madeleine"
    "madeline" "madelyn" "madison" "maegan" "magdalena" "maggie" "maira"
    "makayla" "makenna" "makenzie" "malia" "mallory" "mandy" "mara"
    "maranda" "marcella" "margaret" "margarita" "maria" "mariah" "mariam"
    "mariana" "maribel" "maricela" "marie" "mariel" "mariela" "marilyn"
    "marina" "marisa" "marisela" "marisol" "marissa" "maritza" "marlee"
    "marlena" "marlene" "martha" "martina" "mary" "maura" "maureen" "maya"
    "mayra" "mckayla" "mckenna" "mckenzie" "meagan" "meaghan" "megan"
    "meghan" "melanie" "melina" "melinda" "melisa" "melissa" "melody"
    "meranda" "mercedes" "meredith" "mia" "micaela" "micah" "michaela"
    "michele" "michelle" "mikaela" "mikala" "mikayla" "mindy" "miracle"
    "miranda" "mireya" "miriam" "misty" "mollie" "molly" "monica" "monika"
    "monique" "montana" "morgan" "moriah" "mya" "myra" "myranda" "nadia"
    "nadine" "nancy" "naomi" "natalia" "natalie" "nataly" "natasha"
    "nathalie" "nayeli" "nia" "nichole" "nicole" "nicolette" "nikita"
    "nikki" "nikole" "nina" "noel" "noelle" "noemi" "nora" "norma"
    "octavia" "olga" "olivia" "paige" "paloma" "pamela" "paola" "paris"
    "patrice" "patricia" "paula" "paulina" "pauline" "payton" "perla"
    "peyton" "phoebe" "precious" "princess" "priscilla" "rachael"
    "racheal" "rachel" "rachelle" "randi" "raquel" "raven" "reagan"
    "rebeca" "rebecca" "rebekah" "regan" "regina" "reina" "renee" "reyna"
    "rhiannon" "rhonda" "rikki" "riley" "rita" "robin" "robyn" "rochelle"
    "rocio" "rosa" "rose" "rosemary" "roxana" "roxanne" "ruby" "ruth"
    "ryan" "rylee" "sabrina" "sade" "sadie" "sage" "salina" "sally"
    "samantha" "sandra" "sandy" "sara" "sarah" "sarai" "sarina" "sasha"
    "savanah" "savanna" "savannah" "scarlett" "selena" "selina" "serena"
    "shaina" "shakira" "shana" "shania" "shanice" "shaniqua" "shanna"
    "shannon" "shantel" "sharon" "shauna" "shawna" "shayla" "shayna"
    "shea" "sheena" "sheila" "shelbi" "shelbie" "shelby" "shelly" "sherry"
    "shirley" "shyanne" "sidney" "sierra" "silvia" "simone" "skye"
    "skylar" "skyler" "sofia" "sonia" "sonya" "sophia" "sophie" "stacey"
    "staci" "stacie" "stacy" "stefanie" "stephanie" "stephany" "stevie"
    "stormy" "summer" "susan" "susana" "susanna" "suzanne" "sydnee"
    "sydney" "sydnie" "sylvia" "tabatha" "tabitha" "talia" "tamara"
    "tammy" "tania" "tanisha" "tanya" "tara" "taryn" "tasha" "tatiana"
    "tatum" "tatyana" "tayler" "taylor" "teresa" "terra" "terri" "tess"
    "tessa" "thalia" "theresa" "tia" "tiana" "tianna" "tiara" "tiera"
    "tierra" "tiffani" "tiffanie" "tiffany" "tina" "toni" "tonya" "tori"
    "tracey" "traci" "tracy" "tricia" "trinity" "trisha" "trista" "tyesha"
    "tyler" "tyra" "valeria" "valerie" "vanesa" "vanessa" "veronica"
    "victoria" "virginia" "vivian" "viviana" "wendy" "whitley" "whitney"
    "xiomara" "yadira" "yajaira" "yaritza" "yasmeen" "yasmin" "yasmine"
    "yazmin" "yesenia" "yessenia" "yolanda" "yvette" "yvonne" "zoe"
    "zoey"))

;; Local Variables:
;; coding: utf-8
;; eval: (flycheck-mode -1)
;; End:
