(message "Hi SPAN!")
;; (load "~/src/public/emacs/freerdp-c-style.el")
(load "~/rc/emacs-pjb.el")
(ignore-errors (progn (setf *pjb-current-font-index* 4) (set-current-font)))
(setf *pjb-intervention-firm* '((minint)))
