#!/bin/bash

mkdir -p ~/src/public ~/emacs

cd ~
git clone ssh://pjb@git.informatimago.com/srv/git/public/bin

cd ~/src/public
git clone ssh://pjb@git.informatimago.com/srv/git/public/emacs
git clone ssh://pjb@git.informatimago.com/srv/git/public/lisp

cd ~/emacs
wget http://mumble.net/~campbell/emacs/paredit.el
